import { Metadata } from "next";

export const metadata: Metadata = {
    title: " My Plan | Fit Log",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            My Plan
        </div>
    )
}

export default page