import type { Metadata } from "next";
import { Oswald, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";


export const oswald = Oswald({
  subsets: ["latin"],
});
export const inter = Inter({
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: " Home | Fit Log",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme='dark'
      className={`${oswald.className} ${inter.className} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col bg-black ${inter.className}`}>
        <Navbar></Navbar>

        <main className="flex-1">
          {children}

        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
