import { Oswald, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import WorkoutProvider from "@/context/WorkoutContext";
import { Toaster } from "react-hot-toast";


export const oswald = Oswald({
  subsets: ["latin"],
});
export const inter = Inter({
  subsets: ["latin"],
});



// export const metadata: Metadata = {
//   title: " Home  |  Fit Log",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme='dark'
      className={`${oswald.className} ${inter.className} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col bg-black ${inter.className} `}>
        <WorkoutProvider>

          <Navbar></Navbar>

          <main className="flex-1 lg:px-0 px-2.5">
            {children}

          </main>
          <Footer></Footer>
          <Toaster position="top-right" />
        </WorkoutProvider>
      </body>
    </html>
  );
}
